plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:Name: AppInstance-*
hostnames:
  - ip-address
keyed_groups:
  - prefix: tag
    key: tags.Name
    separator: "_"  
  - key: tags.Role
    prefix: role
cache: yes
cache_path: ~/.ansible/tmp
cache_max_age: 300