---
- hosts: tag_AppInstance_*
  become: yes
  roles:
    - common

- hosts: tag_AppInstance_jenkins
  become: yes
  roles:
    - jenkins

- hosts: tag_AppInstance_sonarqube
  become: yes
  roles:
    - sonarqube