---
- name: Install dependencies
  yum:
    name:
      - unzip
      - wget
    state: present

- name: Create SonarQube directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/sonarqube
    - /opt/sonarqube/data

- name: Set directory permissions
  file:
    path: /opt/sonarqube/data
    owner: 1000
    group: 1000
    recurse: yes

- name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube:lts
    ports:
      - "9000:9000"
    volumes:
      - /opt/sonarqube/data:/opt/sonarqube/data
    restart_policy: always